In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
header = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers = header).text

In [4]:
soup = BeautifulSoup(webpage, 'lxml')

In [5]:
len(soup.find_all('h1'))

1

In [6]:
soup.find_all('h2')[0:5] #all companies' name is written in <h2> html code

[<h2 class="companyListing__title">
 								Companies in India
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="TCS">
 									TCS
 								</h2>,
 <h2 class="companyCardWrapper__companyName" title="Accenture">
 									Accenture
 								</h2>,
 <h2 class="companyCardWrapper__companyName" title="Wipro">
 									Wipro
 								</h2>,
 <h2 class="companyCardWrapper__companyName" title="Cognizant">
 									Cognizant
 								</h2>]

In [7]:
company = soup.find_all('div', class_='companyCardWrapper')
len(company)

20

In [8]:
name=[]
ratings=[]
reviews=[]
l=[]
types=[]
for i in company:
    name.append(i.find('h2').text.strip())
    ratings.append(i.find('div', class_='rating_text').text.strip())
    reviews.append(i.find('span', class_= 'companyCardWrapper__ActionCount').text.strip())
    l.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|'))
for i in range(0, len(l)):
    types.append(l[i][0])

In [9]:
len(soup.find_all('h2'))

24

In [10]:
# for i in soup.find_all('h2')[1:21]:
#     print(i.text.strip()) # stip() removes the space and slash

In [11]:
# rate = soup.find_all('div',class_ = 'rating_text')
# for i in rate:
#     print(i.text.strip())

In [12]:
# review_count = soup.find_all('span', class_= 'companyCardWrapper__ActionCount')
# l = []
# for i in review_count:
#     l.append((i.text))
# r = l[::6]
# for i in r:
#     print(i)

In [13]:
# types = soup.find_all('span', class_='companyCardWrapper__interLinking')
# l = []
# l1 = []
# for i in types:
#     l.append((i.text.strip().split('|')))
# for i in range(0,len(l)):
#     l1.append(l[i][0])
# l1
# for i in l1:
#     print(i)

In [14]:
d = {'Name':name, "Rating":ratings, "No. of Reviews": reviews, "Type of Company":types}
df = pd.DataFrame(d)
df

                      Name Rating No. of Reviews            Type of Company
0                      TCS    3.3           1.2L  IT Services & Consulting
1                Accenture    3.7          74.3k  IT Services & Consulting
2                    Wipro    3.6          65.7k  IT Services & Consulting
3                Cognizant    3.7            62k  IT Services & Consulting
4                Capgemini    3.6            54k  IT Services & Consulting
5                HDFC Bank    3.8          53.1k                   Banking
6                  Infosys    3.5          49.3k  IT Services & Consulting
7                  HCLTech    3.4          46.5k  IT Services & Consulting
8               ICICI Bank    3.9          46.3k                   Banking
9            Tech Mahindra    3.3          43.8k  IT Services & Consulting
10                 Genpact    3.6          42.8k           Analytics & KPO
11                      TP    3.9          39.1k                       BPO
12                     Jio    4.4          33.8k                   Telecom
13               Axis Bank    3.6          33.7k                   Banking
14  Concentrix Corporation    3.6          32.6k                       BPO
15                  Amazon    3.9          31.8k                  Internet
16         Reliance Retail    3.9          27.6k                    Retail
17              iEnergizer    4.6          27.3k                       BPO
18             LTIMindtree    3.6          26.7k  IT Services & Consulting
19                     IBM    3.9            26k  IT Services & Consulting

In [15]:
final = pd.DataFrame()
lf=[]
for j in range(1, 30):
    url = f"https://www.ambitionbox.com/list-of-companies?page={j}"
    header = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"}
    webpage = requests.get(url, headers = header).text
    soup = BeautifulSoup(webpage, 'lxml')
    company = soup.find_all('div', class_='companyCardWrapper')
    name=[]
    ratings=[]
    reviews=[]
    l=[]
    types=[]
    for i in company:
        if type(i) != None:
            name.append(i.find('h2').text.strip())
            ratings.append(i.find('div', class_='rating_text').text.strip())
            reviews.append(i.find('span', class_= 'companyCardWrapper__ActionCount').text.strip())
            l.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|'))
        else:
            break
    for i in range(0, len(l)):
        types.append(l[i][0])
    d = {'Name':name, "Rating":ratings, "No. of Reviews": reviews, "Type of Company":types}
    df = pd.DataFrame(d)
    final = pd.concat([final, df], ignore_index=True)
final

,Name,Rating,No. of Reviews,Type of Company
0,TCS,3.3,1.2L,IT Services & Consulting
1,Accenture,3.7,74.3k,IT Services & Consulting
2,Wipro,3.6,65.7k,IT Services & Consulting
3,Cognizant,3.7,62k,IT Services & Consulting
4,Capgemini,3.6,54k,IT Services & Consulting
...,...,...,...,...
575,USV,4.0,1.8k,Pharma
576,LivSpace,3.3,1.8k,Architecture & Interior Design
577,XBP Global,3.2,1.8k,Internet
578,Tata Communications Transformation Services,3.8,1.8k,Telecom
579,HDFC Securities,3.4,1.8k,Financial Services

In [16]:
type(final)

pandas.core.frame.DataFrame

In [17]:
final.shape

(580, 4)

In [18]:
final.to_csv("C:/Users/yaagh aiyappa/OneDrive/ドキュメント/csv_files/Top_Companies.csv")