In [1]:
import json
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import http.client

conn = http.client.HTTPSConnection("free-api-live-football-data.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "6c56a19407msh30b750159c8d003p16b8e9jsn577ef409f4aa",
    'x-rapidapi-host': "free-api-live-football-data.p.rapidapi.com",
    'Content-Type': "application/json"
}

conn.request("GET", "/football-players-search?search=m", headers=headers)

res = conn.getresponse()
data = res.read()

d = data.decode("utf-8")
a = json.loads(d)
a

{'status': 'success',
 'response': {'suggestions': [{'type': 'player',
    'id': '701154',
    'score': 301297,
    'name': 'Kylian Mbappé',
    'isCoach': False,
    'teamId': 8633,
    'teamName': 'Real Madrid'},
   {'type': 'player',
    'id': '292462',
    'score': 301159,
    'name': 'Mohamed Salah',
    'isCoach': False,
    'teamId': 8650,
    'teamName': 'Liverpool'},
   {'type': 'player',
    'id': '30981',
    'score': 301149,
    'name': 'Lionel Messi',
    'isCoach': False,
    'teamId': 960720,
    'teamName': 'Inter Miami CF'},
   {'type': 'player',
    'id': '923312',
    'score': 301098,
    'name': 'Bryan Mbeumo',
    'isCoach': False,
    'teamId': 10260,
    'teamName': 'Manchester United'},
   {'type': 'player',
    'id': '831489',
    'score': 301096,
    'name': 'Alexis Mac Allister',
    'isCoach': False,
    'teamId': 8650,
    'teamName': 'Liverpool'},
   {'type': 'player',
    'id': '1158945',
    'score': 301094,
    'name': 'Nuno Mendes',
    'isCoach': False,
    'teamId': 9847,
    'teamName': 'Paris Saint-Germain'},
   {'type': 'player',
    'id': '1029063',
    'score': 301093,
    'name': 'Michael Olise',
    'isCoach': False,
    'teamId': 9823,
    'teamName': 'Bayern München'},
   {'type': 'player',
    'id': '1156141',
    'score': 301093,
    'name': 'Jamal Musiala',
    'isCoach': False,
    'teamId': 9823,
    'teamName': 'Bayern München'},
   {'type': 'player',
    'id': '534670',
    'score': 301092,
    'name': 'Martin Ødegaard',
    'isCoach': False,
    'teamId': 9825,
    'teamName': 'Arsenal'},
   {'type': 'player',
    'id': '1031325',
    'score': 301092,
    'name': 'Martín Zubimendi',
    'isCoach': False,
    'teamId': 9825,
    'teamName': 'Arsenal'},
   {'type': 'player',
    'id': '1137668',
    'score': 301091,
    'name': 'Moisés Caicedo',
    'isCoach': False,
    'teamId': 8455,
    'teamName': 'Chelsea'},
   {'type': 'player',
    'id': '863098',
    'score': 301083,
    'name': 'Matheus Cunha',
    'isCoach': False,
    'teamId': 10260,
    'teamName': 'Manchester United'},
   {'type': 'player',
    'id': '839204',
    'score': 301080,
    'name': 'Omar Marmoush',
    'isCoach': False,
    'teamId': 8456,
    'teamName': 'Manchester City'},
   {'type': 'player',
    'id': '844425',
    'score': 301066,
    'name': 'Marc Guéhi',
    'isCoach': False,
    'teamId': 8456,
    'teamName': 'Manchester City'},
   {'type': 'player',
    'id': '873289',
    'score': 301048,
    'name': 'Marc Cucurella',
    'isCoach': False,
    'teamId': 8455,
    'teamName': 'Chelsea'},
   {'type': 'player',
    'id': '1607566',
    'score': 301042,
    'name': 'Franco Mastantuono',
    'isCoach': False,
    'teamId': 8633,
    'teamName': 'Real Madrid'},
   {'type': 'player',
    'id': '1021586',
    'score': 301034,
    'name': 'Gabriel Martinelli',
    'isCoach': False,
    'teamId': 9825,
    'teamName': 'Arsenal'},
   {'type': 'player',
    'id': '847983',
    'score': 301026,
    'name': 'Lisandro Martínez',
    'isCoach': False,
    'teamId': 10260,
    'teamName': 'Manchester United'},
   {'type': 'player',
    'id': '1084981',
    'score': 301020,
    'name': 'Noni Madueke',
    'isCoach': False,
    'teamId': 9825,
    'teamName': 'Arsenal'},
   {'type': 'player',
    'id': '1574189',
    'score': 301019,
    'name': 'Senny Mayulu',
    'isCoach': False,
    'teamId': 9847,
    'teamName': 'Paris Saint-Germain'},
   {'type': 'player',
    'id': '1292810',
    'score': 301018,
    'name': 'Kobbie Mainoo',
    'isCoach': False,
    'teamId': 10260,
    'teamName': 'Manchester United'},
   {'type': 'player',
    'id': '769895',
    'score': 301018,
    'name': 'Matthijs de Ligt',
    'isCoach': False,
    'teamId': 10260,
    'teamName': 'Manchester United'},
   {'type': 'player',
    'id': '1195281',
    'score': 301016,
    'name': 'Milos Kerkez',
    'isCoach': False,
    'teamId': 8650,
    'teamName': 'Liverpool'},
   {'type': 'player',
    'id': '955529',
    'score': 301009,
    'name': 'Matheus Nunes',
    'isCoach': False,
    'teamId': 8456,
    'teamName': 'Manchester City'},
   {'type': 'player',
    'id': '696365',
    'score': 301007,
    'name': 'Marcus Rashford',
    'isCoach': False,
    'teamId': 8634,
    'teamName': 'Barcelona'},
   {'type': 'player',
    'id': '976506',
    'score': 301002,
    'name': 'Mykhaylo Mudryk',
    'isCoach': False,
    'teamId': 8455,
    'teamName': 'Chelsea'},
   {'type': 'player',
    'id': '1406436',
    'score': 301000,
    'name': 'Myles Lewis-Skelly',
    'isCoach': False,
    'teamId': 9825,
    'teamName': 'Arsenal'},
   {'type': 'player',
    'id': '1197250',
    'score': 300999,
    'name': 'Malo Gusto',
    'isCoach': False,
    'teamId': 8455,
    'teamName': 'Chelsea'},
   {'type': 'player',
    'id': '1573126',
    'score': 300999,
    'name': 'Marc Bernal',
    'isCoach': False,
    'teamId': 8634,
    'teamName': 'Barcelona'},
   {'type': 'player',
    'id': '750032',
    'score': 300998,
    'name': 'Mason Mount',
    'isCoach': False,
    'teamId': 10260,
    'teamName': 'Manchester United'},
   {'type': 'player',
    'id': '948800',
    'score': 300996,
    'name': 'Giorgi Mamardashvili',
    'isCoach': False,
    'teamId': 8650,
    'teamName': 'Liverpool'},
   {'type': 'player',
    'id': '1035614',
    'score': 300992,
    'name': 'Manuel Ugarte',
    'isCoach': False,
    'teamId': 10260,
    'teamName': 'Manchester United'},
   {'type': 'player',
    'id': '574645',
    'score': 300992,
    'name': 'Mikel Merino',
    'isCoach': False,
    'teamId': 9825,
    'teamName': 'Arsenal'},
   {'type': 'player',
    'id': '267365',
    'score': 300988,
    'name': 'Marquinhos',
    'isCoach': False,
    'teamId': 9847,
    'teamName': 'Paris Saint-Germain'},
   {'type': 'player',
    'id': '844415',
    'score': 300985,
    'name': 'Éder Militao',
    'isCoach': False,
    'teamId': 8633,
    'teamName': 'Real Madrid'},
   {'type': 'player',
    'id': '1298907',
    'score': 300974,
    'name': 'Cristhian Mosquera',
    'isCoach': False,
    'teamId': 9825,
    'teamName': 'Arsenal'},
   {'type': 'player',
    'id': '828159',
    'score': 300970,
    'name': 'Min-Jae Kim',
    'isCoach': False,
    'teamId': 9823,
    'teamName': 'Bayern München'},
   {'type': 'player',
    'id': '1384883',
    'score': 300967,
    'name': 'Marc Casadó',
    'isCoach': False,
    'teamId': 8634,
    'teamName': 'Barcelona'},
   {'type': 'player',
    'id': '848290',
    'score': 300063,
    'name': 'Enock Mwepu',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '428947',
    'score': 300045,
    'name': 'Santi Mina',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '171698',
    'score': 300030,
    'name': 'Joel Matip',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '113672',
    'score': 300014,
    'name': 'Mateo Pablo Musacchio',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '231592',
    'score': 300013,
    'name': 'Aaron Mooy',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '161683',
    'score': 300012,
    'name': 'Konstantinos Manolas',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '128381',
    'score': 300010,
    'name': 'Marlos',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '281863',
    'score': 300007,
    'name': 'Marcelinho',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '111787',
    'score': 300007,
    'name': 'Mathieu Dossevi',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '267373',
    'score': 300007,
    'name': 'Maycon',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '184999',
    'score': 300007,
    'name': 'Shkodran Mustafi',
    'isCoach': False,
    'teamName': ''},
   {'type': 'player',
    'id': '229759',
    'score': 300006,
    'name': 'Marvin Plattenhardt',
    'isCoach': False,
    'teamName': ''}]}}

In [ ]:
df = pd.DataFrame(a['response']['suggestions'])
df.head()

,type,id,score,name,isCoach,teamId,teamName
0,player,701154,301297,Kylian Mbappé,False,8633.0,Real Madrid
1,player,292462,301159,Mohamed Salah,False,8650.0,Liverpool
2,player,30981,301149,Lionel Messi,False,960720.0,Inter Miami CF
3,player,923312,301098,Bryan Mbeumo,False,10260.0,Manchester United
4,player,831489,301096,Alexis Mac Allister,False,8650.0,Liverpool

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   type      50 non-null     object
 1   id        50 non-null     object
 2   score     50 non-null     int64
 3   name      50 non-null     object
 4   isCoach   50 non-null     bool
 5   teamId    38 non-null     float64
 6   teamName  50 non-null     object
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 2.5+ KB

In [ ]:
df1 = df.drop(columns = ['type'])
df1

,id,score,name,isCoach,teamId,teamName
0,701154,301297,Kylian Mbappé,False,8633.0,Real Madrid
1,292462,301159,Mohamed Salah,False,8650.0,Liverpool
2,30981,301149,Lionel Messi,False,960720.0,Inter Miami CF
3,923312,301098,Bryan Mbeumo,False,10260.0,Manchester United
4,831489,301096,Alexis Mac Allister,False,8650.0,Liverpool
5,1158945,301094,Nuno Mendes,False,9847.0,Paris Saint-Germain
6,1029063,301093,Michael Olise,False,9823.0,Bayern München
7,1156141,301093,Jamal Musiala,False,9823.0,Bayern München
8,534670,301092,Martin Ødegaard,False,9825.0,Arsenal
9,1031325,301092,Martín Zubimendi,False,9825.0,Arsenal
10,1137668,301091,Moisés Caicedo,False,8455.0,Chelsea
11,863098,301083,Matheus Cunha,False,10260.0,Manchester United
12,839204,301080,Omar Marmoush,False,8456.0,Manchester City
13,844425,301066,Marc Guéhi,False,8456.0,Manchester City
14,873289,301048,Marc Cucurella,False,8455.0,Chelsea
15,1607566,301042,Franco Mastantuono,False,8633.0,Real Madrid
16,1021586,301034,Gabriel Martinelli,False,9825.0,Arsenal
17,847983,301026,Lisandro Martínez,False,10260.0,Manchester United
18,1084981,301020,Noni Madueke,False,9825.0,Arsenal
19,1574189,301019,Senny Mayulu,False,9847.0,Paris Saint-Germain
20,1292810,301018,Kobbie Mainoo,False,10260.0,Manchester United
21,769895,301018,Matthijs de Ligt,False,10260.0,Manchester United
22,1195281,301016,Milos Kerkez,False,8650.0,Liverpool
23,955529,301009,Matheus Nunes,False,8456.0,Manchester City
24,696365,301007,Marcus Rashford,False,8634.0,Barcelona
25,976506,301002,Mykhaylo Mudryk,False,8455.0,Chelsea
26,1406436,301000,Myles Lewis-Skelly,False,9825.0,Arsenal
27,1197250,300999,Malo Gusto,False,8455.0,Chelsea
28,1573126,300999,Marc Bernal,False,8634.0,Barcelona
29,750032,300998,Mason Mount,False,10260.0,Manchester United
30,948800,300996,Giorgi Mamardashvili,False,8650.0,Liverpool
31,1035614,300992,Manuel Ugarte,False,10260.0,Manchester United
32,574645,300992,Mikel Merino,False,9825.0,Arsenal
33,267365,300988,Marquinhos,False,9847.0,Paris Saint-Germain
34,844415,300985,Éder Militao,False,8633.0,Real Madrid
35,1298907,300974,Cristhian Mosquera,False,9825.0,Arsenal
36,828159,300970,Min-Jae Kim,False,9823.0,Bayern München
37,1384883,300967,Marc Casadó,False,8634.0,Barcelona
38,848290,300063,Enock Mwepu,False,NaN,
39,428947,300045,Santi Mina,False,NaN,
40,171698,300030,Joel Matip,False,NaN,
41,113672,300014,Mateo Pablo Musacchio,False,NaN,
42,231592,300013,Aaron Mooy,False,NaN,
43,161683,300012,Konstantinos Manolas,False,NaN,
44,128381,300010,Marlos,False,NaN,
45,281863,300007,Marcelinho,False,NaN,
46,111787,300007,Mathieu Dossevi,False,NaN,
47,267373,300007,Maycon,False,NaN,
48,184999,300007,Shkodran Mustafi,False,NaN,
49,229759,300006,Marvin Plattenhardt,False,NaN,

In [ ]:
df2 = df1.iloc[0:38]

In [ ]:
df2.to_csv("C:/Users/yaagh aiyappa/OneDrive/ドキュメント/csv_files/FootBallers.csv")
print('Done')

Done