In [93]:
import pandas as pd
import numpy as np

In [94]:
df = pd.read_csv(r"C:\Users\yaagh aiyappa\OneDrive\ドキュメント\csv_files\MinimumLife_Data.csv",
                index_col='PartNo')

In [95]:
df = df.drop('Unnamed: 0', axis=1)

In [96]:
df.head()

          Dia2  Moment  Force    LifeMinimum
PartNo
DP 0    30.000  400000   8000   33177.988210
DP 1    20.125  335750   6355    2312.609429
DP 2    20.375   92750   4825  152895.636500
DP 3    20.625  205250   8875    7870.191146
DP 4    20.875  362750   2665    2887.874963

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:3],
                                                   df['LifeMinimum'],
                                                   test_size=0.1)

In [99]:
x_train

          Dia2  Moment  Force
PartNo
DP 18   24.375  187250   9415
DP 76   38.875  407750   3115
DP 84   40.875  286250   3475
DP 94   43.375  277250   8965
DP 62   35.375  470750   9055
...        ...     ...    ...
DP 63   35.625  106250   6265
DP 86   41.375  236750   6895
DP 81   40.125   65750   2035
DP 25   26.125  304250   6985
DP 32   27.875  209750   7075

[90 rows x 3 columns]

In [124]:
%%html
<h1> LinearRegression Without Scaling </h1>

In [100]:
from sklearn.linear_model import LinearRegression

In [118]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [119]:
lr.score(x_train, y_train)

0.8188313015042195

In [120]:
y_pred = lr.predict(x_test)
y_pred.shape

(10,)

In [121]:
lr.score(x_test,y_test)

0.6243678533543999

In [122]:
from sklearn.metrics import r2_score

In [123]:
R2_score = r2_score(y_test,y_pred)
R2_score

0.6243678533543999

In [133]:
from sklearn.ensemble import RandomForestRegressor

In [139]:
rfr = RandomForestRegressor()
rfr.fit(x_train, y_train)

RandomForestRegressor()

In [140]:
rfr.score(x_train,y_train)

0.9804287742529388

In [141]:
y_pred2 = rfr.predict(x_test)

In [142]:
R2_score2 = r2_score(y_test,y_pred)
R2_score2

0.6243678533543999

In [143]:
print(set(y_test), set(y_pred))

{1000000.0, 134125.6664, 179374.9802, 59887.80733, 24118.52393, 33655.92837, 445686.0313, 62939.69333} {np.float64(204160.51043636072), np.float64(147143.30124500848), np.float64(459561.89597913483), np.float64(617004.7302572104), np.float64(321229.6250105341), np.float64(263253.2656981583), np.float64(307222.77185251925), np.float64(748826.4934870937), np.float64(1193980.3728466392), np.float64(1499613.5704413652)}