In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\yaagh aiyappa\OneDrive\ドキュメント\csv_files\DesignPointLog2.csv")

In [5]:
df.sample(5)

     Name  P10     P11     P16  P12   P17             P18
21  DP 21   50  25.125  389750   50  2485     9288.657213
46  DP 47   50  31.625  232250   50  3835   445686.031300
48  DP 49   50  32.125  268250   50  7885   179374.980200
53  DP 54   50  33.375  214250   50  1405  1000000.000000
98  DP 99   50  44.625   56750   50  5545  1000000.000000

In [22]:
df = df.rename(columns={'Name':'PartNo','P10':'Dia1','P11':'Dia2','P16':'Moment','P12':'Dia3','P17':'Force','P18':'LifeMinimum'})

In [23]:
df = df.drop(['Dia1','Dia3'], axis=1)

In [24]:
df.sample(5)

   PartNo    Dia2  Moment  Force     LifeMinimum
65  DP 66  36.375  313250   9325   705881.117200
93  DP 94  43.375  277250   8965  1000000.000000
28  DP 28  26.875  430250   8065     9423.941455
19  DP 19  24.625  497750   1675     4304.267793
67  DP 68  36.875  151250   6715  1000000.000000